- hosts: nginx   
    
  become: yes    
  become_user: root    
  become_method: sudo    
    
  tasks:
  - name: Install nginx
    apt:
      name: nginx
      update_cache: yes

  - name: Create nginx config
    shell: touch /etc/nginx/sites-enabled/default

  - name: Add lines to nginx config
    blockinfile:
      path: /etc/nginx/sites-enabled/default
      block: |
        upstream myapp {
          least_conn;
          server {{ hostvars.tomcat1.ansible_host }}:8080;
          server {{ hostvars.tomcat2.ansible_host }}:8080;
          server {{ hostvars.tomcat3.ansible_host }}:8080;
        }

        server {
          listen 80;
          listen [::]:80;

          #Configure Nginx to handle dynamic page requests The jsp file request is forwarded to the Tomcat server for processing
          location ~ .*\.jsp$ {
            proxy_pass http://myapp;
            proxy_set_header HOST $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port $server_port;
          }

          #Configure Nginx to handle still picture requests
          location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|css)$ {
            root /usr/local/nginx/html/img;
            expires 10d;
          }

          location / {
            root html;
            index index.html index.htm;
          }
        }

  - name: Restart nginx
    systemd:
      name: nginx
      state: restarted
